name: 'VPM package listing generator'
description: 'Generates or augments a VPM package listing with releases from a specified repository'
author: bd_
inputs:
  output:
    required: true
    description: 'output path'
  repository:
    required: false
    description: 'Repository to obtain releases from'
    default: ${{ github.repository }}
  include_prereleases:
    required: false
    default: false
  package:
    required: true
    description: The VPM package name to include
  token:
    required: false
    description: The github auth token
    default: ${{ secrets.GITHUB_TOKEN }}
runs:
  using: 'node18'
  main: 'dist/index.js'
